[theme]
base = "light"
# General color setup
textColor = "#3f3f46"
primaryColor = "#60a5fa"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
# Widgets
showWidgetBorder = true
borderColor = "#eeeef0"
# Base text
font = "Inter"
baseFontWeight = 400
baseFontSize = 14
# Heading text
headingFont = "Inter"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1rem", "1rem", "0.8rem", "0.8rem"]

[[theme.fontFaces]]
family = "Inter"
style = "normal"
weight = "100 900"
url = "https://fonts.gstatic.com/s/inter/v19/UcCo3FwrK3iLTcviYwYZ8UA3.woff2"

[[theme.fontFaces]]
family = "Inter"
style = "italic"
weight = "100 900"
url = "https://fonts.gstatic.com/s/inter/v19/UcCm3FwrK3iLTcvnUwQT9mI1F54.woff2"